defmodule DynRelRepro.Repo.Migrations.ResourcesSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :included_tags, :text, null: false
    end

    create table(:elements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tags, {:array, :text}, null: false
    end
  end

  def down do
    drop table(:elements)

    drop table(:groups)
  end
end
